# Generated by Django 5.1.3 on 2024-12-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_registro', models.CharField(max_length=255)),
                ('concepto', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_registro', models.CharField(choices=[('convenio_ingreso', 'Convenio Ingreso'), ('convenio_egreso', 'Convenio Egreso'), ('aporte_ingreso', 'Aporte Ingreso'), ('aporte_egreso', 'Aporte Egreso')], max_length=50)),
                ('folio', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='registros.registro')),
            ],
        ),
    ]
