# Generated by Django 5.1.3 on 2024-12-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_registro_documento_firmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='debe',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='documento_firmado',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='haber',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='total',
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='registros.registro')),
            ],
        ),
    ]
