# Generated by Django 5.1.3 on 2024-12-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_remove_registro_debe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción', null=True),
        ),
    ]
