# Generated by Django 5.1.4 on 2024-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_registro_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='documento_firmado',
            field=models.FileField(blank=True, null=True, upload_to='documentos_firmados/', verbose_name='Documento Firmado'),
        ),
    ]
