# Generated by Django 5.1.4 on 2024-12-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_registro_documento_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivoadjunto',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
